  
name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)
# Pipeline triggers on any branch and tag
parameters:
  - name: 'mavenContainer'
    default: 'maven:3-jdk-11'
trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

resources:
  containers:
  - container: 'ubuntu_container_for_build_deply_to_nexus'
    image: 'ubuntu:latest'
  repositories:
  - repository: templates
    type: github
    name: statisticsnorway/azure-pipelines-templates
    ref: refs/tags/0.0.10
    endpoint: statisticsnorway (6)

# Pipeline will be run on this base image
pool:
  vmImage: 'ubuntu-latest'

# Variables global to this pipeline
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
variables:
  # Variables defined in Pipelines->Library->Variable Groups in your project in
  # Azure Pipelines
  - group: Hemmeligheter
  # Variables defined here
  - name:  MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository
  - name: MAVEN_OPTS
    value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

# Job which runs mvn build, mvn install,
jobs:
  - job: buildTest
    displayName: 'compile deploy app'
    container: 'maven:3-jdk-11'
    # Job condition: Run these jobs on any branch, but not on tags
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    # Steps in this Job
    steps:
    - template: maven/task-authenticate.yml@templates

    - template: maven/task-cache.yml@templates

    - task: Maven@3
      displayName: 'Maven compile'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'compile'
        options: '-P ssb-bip,coverage -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode $(MAVEN_OPTS)'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m'
        mavenAuthenticateFeed: false
        effectivePomSkip: false

    - template: maven/task-test-and-verify.yml@templates
    - template: maven/task-sonar-analyze.yml@templates

    - template: maven/task-install-and-deploy-to-nexus.yml@templates